info:
  component: Edge Server


server:
  port: 8766

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring.sleuth.sampler.percentage: 1.0

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    api-usuarios:
      path: /usuarios/v1/**
      serviceId: api-usuarios
      stripPrefix: false
      sensitiveHeaders:

    api-confirmaciones:
      path: /confirmaciones/v1/**
      serviceId: api-confirmaciones
      stripPrefix: false
      sensitiveHeaders:

    api-amigos:
      path: /amigos/v1/**
      serviceId: api-amigos
      stripPrefix: false
      sensitiveHeaders:

    api-solicitudes:
      path: /solicitudes/v1/**
      serviceId: api-solicitudes
      stripPrefix: false
      sensitiveHeaders:

    api-posts:
      path: /posts/v1/**
      serviceId: api-posts
      stripPrefix: false
      sensitiveHeaders:

    notification-service:
      path: /notification/**
      serviceId: notification-service
      stripPrefix: false
      sensitiveHeaders:

    ui-platform:
      path: /**
      serviceId: ui-platform
      stripPrefix: false
      sensitiveHeaders: